[build]
  base = "rock-paper-scissors-chase"
  command = "npm run build"
  publish = "dist"

# SPA 重定向規則
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 處理 API 路由（如果有的話）
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200